apiVersion: 1

datasources:
  - name: K6 InfluxDB
    uid: P6C0B0CFA7252F455  # JSON과 반드시 동일
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    database: k6
    isDefault: true
    jsonData:
      httpMode: POST

  - name: Prometheus
    uid: PROM
    type: prometheus
    access: proxy
    url: http://prometheus:9090